# Generated by Django 3.1.1 on 2020-11-15 07:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qoute', models.CharField(max_length=700)),
                ('qoute_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('userp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'ordering': ('-qoute_date',),
            },
        ),
    ]
